LANGUAGES = [
    ('Afrikaans', 'afr'),
    ('Albanian', 'sqi'),
    ('Amharic', 'amh'),
    ('Arabic', 'ara'),
    ('Armenian', 'hye'),
    ('Assamese', 'asm'),
    ('Azerbaijani', 'aze'),
    ('Azerbaijani - Cyrillic', 'aze_cyrl'),
    ('Basque', 'eus'),
    ('Belarusian', 'bel'),
    ('Bengali', 'ben'),
    ('Bihari', 'bih'),
    ('Bosnian', 'bos'),
    ('Breton', 'bre'),
    ('Bulgarian', 'bul'),
    ('Burmese', 'mya'),
    ('Catalan', 'cat'),
    ('Cebuano', 'ceb'),
    ('Cherokee', 'chr'),
    ('Chinese (Simplified)', 'chi_sim'),
    ('Chinese (Simplified, Vertical)', 'chi_sim_vert'),
    ('Chinese (Traditional)', 'chi_tra'),
    ('Chinese (Traditional, Vertical)', 'chi_tra_vert'),
    ('Corsican', 'cos'),
    ('Croatian', 'hrv'),
    ('Czech', 'ces'),
    ('Danish', 'dan'),
    ('Divehi', 'div'),
    ('Dutch', 'nld'),
    ('Dzongkha', 'dzo'),
    ('English', 'eng'),
    ('Esperanto', 'epo'),
    ('Estonian', 'est'),
    ('Faroese', 'fao'),
    ('Fijian', 'fij'),
    ('Finnish', 'fin'),
    ('French', 'fra'),
    ('Frankish', 'frk'),
    ('French (Old)', 'frm'),
    ('Frisian', 'fry'),
    ('Galician', 'glg'),
    ('Georgian', 'kat'),
    ('Georgian (Old)', 'kat_old'),
    ('German', 'deu'),
    ('Greek', 'ell'),
    ('Greek (Ancient)', 'grc'),
    ('Gujarati', 'guj'),
    ('Haitian', 'hat'),
    ('Hausa', 'hau'),
    ('Hawaiian', 'haw'),
    ('Hebrew', 'heb'),
    ('Hindi', 'hin'),
    ('Hungarian', 'hun'),
    ('Icelandic', 'isl'),
    ('Igbo', 'ibo'),
    ('Indonesian', 'ind'),
    ('Inuktitut', 'iku'),
    ('Irish', 'gle'),
    ('Italian', 'ita'),
    ('Italian (Old)', 'ita_old'),
    ('Japanese', 'jpn'),
    ('Japanese (Vertical)', 'jpn_vert'),
    ('Javanese', 'jav'),
    ('Kannada', 'kan'),
    ('Kazakh', 'kaz'),
    ('Khmer', 'khm'),
    ('Kinyarwanda', 'kin'),
    ('Korean', 'kor'),
    ('Kurdish (Kurmanji)', 'kmr'),
    ('Kyrgyz', 'kir'),
    ('Lao', 'lao'),
    ('Latin', 'lat'),
    ('Latvian', 'lav'),
    ('Lithuanian', 'lit'),
    ('Luxembourgish', 'ltz'),
    ('Macedonian', 'mkd'),
    ('Malagasy', 'mlg'),
    ('Malay', 'msa'),
    ('Malayalam', 'mal'),
    ('Maltese', 'mlt'),
    ('Maori', 'mri'),
    ('Marathi', 'mar'),
    ('Mongolian', 'mon'),
    ('Nepali', 'nep'),
    ('Norwegian', 'nor'),
    ('Occitan', 'oci'),
    ('Oriya', 'ori'),
    ('Oromo', 'orm'),
    ('Ossetian', 'oss'),
    ('Pali', 'pli'),
    ('Pashto', 'pus'),
    ('Persian', 'fas'),
    ('Polish', 'pol'),
    ('Portuguese', 'por'),
    ('Punjabi', 'pan'),
    ('Quechua', 'que'),
    ('Romanian', 'ron'),
    ('Russian', 'rus'),
    ('Sanskrit', 'san'),
    ('Serbian', 'srp'),
    ('Serbian - Latin', 'srp_latn'),
    ('Sesotho', 'sot'),
    ('Shona', 'sna'),
    ('Sindhi', 'snd'),
    ('Sinhala', 'sin'),
    ('Slovak', 'slk'),
    ('Slovenian', 'slv'),
    ('Somali', 'som'),
    ('Sotho', 'sot'),
    ('Spanish', 'spa'),
    ('Spanish (Old)', 'spa_old'),
    ('Sundanese', 'sun'),
    ('Swahili', 'swa'),
    ('Swedish', 'swe'),
    ('Tagalog', 'tgl'),
    ('Tahitian', 'tah'),
    ('Tajik', 'tgk'),
    ('Tamil', 'tam'),
    ('Tatar', 'tat'),
    ('Telugu', 'tel'),
    ('Thai', 'tha'),
    ('Tigrinya', 'tir'),
    ('Tongan', 'ton'),
    ('Turkish', 'tur'),
    ('Turkmen', 'tuk'),
    ('Uighur', 'uig'),
    ('Ukrainian', 'ukr'),
    ('Urdu', 'urd'),
    ('Uzbek', 'uzb'),
    ('Uzbek - Cyrillic', 'uzb_cyrl'),
    ('Vietnamese', 'vie'),
    ('Welsh', 'cym'),
    ('Wolof', 'wol'),
    ('Xhosa', 'xho'),
    ('Yiddish', 'yid'),
    ('Yoruba', 'yor'),
    ('Zulu', 'zul')

]