name: Run Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Tesseract OCR
      run: |
        choco install tesseract

    - name: Download Tesseract language data
      run: |
        $tessdata_url = "https://github.com/tesseract-ocr/tessdata_best/raw/main/afr.traineddata"
        $tessdata_dir = "${env:TESSDATA_PREFIX}\tessdata"
        New-Item -ItemType Directory -Force -Path $tessdata_dir
        Invoke-WebRequest -Uri $tessdata_url -OutFile "${tessdata_dir}\afr.traineddata"

    - name: Install system dependencies
      run: choco install pulseaudio

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run pytest
      run: pytest tests
