name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Tesseract OCR
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr
        sudo apt-get install -y libtesseract-dev
        
    - name: Create tessdata directory
      run: sudo mkdir -p /usr/share/tessdata

    - name: Download Tesseract language data
      run: |
        for lang in afr sqi amh ara hye aze eus bel ben bos bul cat ceb chi_sim chi_tra cos hrv ces dan nld eng epo est fin fra fry glg kat deu ell guj hat hau haw heb hin hun isl ibo ind gle ita jpn jav kan kaz khm kor kmr kir lao lat lav lit ltz mkd mlg msa mal mlt mri mar mon nep nor pus fas pol por pan ron rus srp sot sna snd sin slk slv som spa sun swa swe tgl tgk tam tel tha tur ukr urd uzb vie cym xho yid yor zul; do
          sudo wget -P /usr/share/tessdata https://github.com/tesseract-ocr/tessdata_best/raw/master/$lang.traineddata
        done


    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpulse-mainloop-glib0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest tests
