name: Run Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Tesseract OCR
      run: |
        choco install tesseract
        choco install tesseract-ocr-afr

    - name: Install system dependencies
      run: choco install pulseaudio

    - name: Install xvfb
      run: choco install xvfb

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run pytest
      run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' pytest tests
