name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Tesseract OCR
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr
        sudo apt-get install -y libtesseract-dev
        sudo apt-get install -y tesseract-ocr-afr tesseract-ocr-sqi tesseract-ocr-amh tesseract-ocr-ara tesseract-ocr-hye tesseract-ocr-aze tesseract-ocr-eus tesseract-ocr-bel tesseract-ocr-ben tesseract-ocr-bos tesseract-ocr-bul tesseract-ocr-cat tesseract-ocr-ceb tesseract-ocr-chi-sim tesseract-ocr-chi-tra tesseract-ocr-cos tesseract-ocr-hrv tesseract-ocr-ces tesseract-ocr-dan tesseract-ocr-nld tesseract-ocr-eng tesseract-ocr-epo tesseract-ocr-est tesseract-ocr-fin tesseract-ocr-fra tesseract-ocr-fry tesseract-ocr-glg tesseract-ocr-kat tesseract-ocr-deu tesseract-ocr-ell tesseract-ocr-guj tesseract-ocr-hat tesseract-ocr-hau tesseract-ocr-haw tesseract-ocr-heb tesseract-ocr-hin tesseract-ocr-hun tesseract-ocr-isl tesseract-ocr-ibo tesseract-ocr-ind tesseract-ocr-gle tesseract-ocr-ita tesseract-ocr-jpn tesseract-ocr-jav tesseract-ocr-kan tesseract-ocr-kaz tesseract-ocr-khm tesseract-ocr-kor tesseract-ocr-kmr tesseract-ocr-kir tesseract-ocr-lao tesseract-ocr-lat tesseract-ocr-lav tesseract-ocr-lit tesseract-ocr-ltz tesseract-ocr-mkd tesseract-ocr-mlg tesseract-ocr-msa tesseract-ocr-mal tesseract-ocr-mlt tesseract-ocr-mri tesseract-ocr-mar tesseract-ocr-mon tesseract-ocr-nep tesseract-ocr-nor tesseract-ocr-pus tesseract-ocr-fas tesseract-ocr-pol tesseract-ocr-por tesseract-ocr-pan tesseract-ocr-ron tesseract-ocr-rus tesseract-ocr-srp tesseract-ocr-sot tesseract-ocr-sna tesseract-ocr-snd tesseract-ocr-sin tesseract-ocr-slk tesseract-ocr-slv tesseract-ocr-som tesseract-ocr-spa tesseract-ocr-sun tesseract-ocr-swa tesseract-ocr-swe tesseract-ocr-tgl tesseract-ocr-tgk tesseract-ocr-tam tesseract-ocr-tel tesseract-ocr-tha tesseract-ocr-tur tesseract-ocr-ukr tesseract-ocr-urd tesseract-ocr-uzb tesseract-ocr-vie tesseract-ocr-cym tesseract-ocr-xho tesseract-ocr-yid tesseract-ocr-yor tesseract-ocr-zul
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpulse-mainloop-glib0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest tests
