name: Run Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install CMake
      run: choco install cmake

    - name: Build Tesseract
      run: |
        git clone https://github.com/tesseract-ocr/tesseract.git
        cd tesseract
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 ..
        cmake --build . --config Release --target INSTALL


    - name: Download tessdata
      run: |
        mkdir -p ${{env.TESSDATA_PREFIX}}
        cd ${{env.TESSDATA_PREFIX}}
        curl -LO https://github.com/tesseract-ocr/tessdata_fast/raw/master/eng.traineddata



    - name: Install system dependencies
      run: choco install pulseaudio

    - name: Install xvfb
      run: choco install xvfb

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run pytest
      run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' pytest tests
