name: Run Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Tesseract OCR
      run: |
        choco install tesseract
        choco install tesseract-afr tesseract-sqi tesseract-amh tesseract-ara tesseract-hye tesseract-aze tesseract-eus tesseract-bel tesseract-ben tesseract-bos tesseract-bul tesseract-cat tesseract-ceb tesseract-chi-sim tesseract-chi-tra tesseract-cos tesseract-hrv tesseract-ces tesseract-dan tesseract-nld tesseract-eng tesseract-epo tesseract-est tesseract-fin tesseract-fra tesseract-fry tesseract-glg tesseract-kat tesseract-deu tesseract-ell tesseract-guj tesseract-hat tesseract-heb tesseract-hin tesseract-hun tesseract-isl tesseract-ind tesseract-gle tesseract-ita tesseract-jpn tesseract-jav tesseract-kan tesseract-kaz tesseract-khm tesseract-kor tesseract-kmr tesseract-kir tesseract-lao tesseract-lat tesseract-lav tesseract-lit tesseract-ltz tesseract-mkd tesseract-msa tesseract-mal tesseract-mlt tesseract-mri tesseract-mar tesseract-mon tesseract-nep tesseract-nor tesseract-pus tesseract-fas tesseract-pol tesseract-por tesseract-pan tesseract-ron tesseract-rus tesseract-srp tesseract-snd tesseract-sin tesseract-slk tesseract-slv tesseract-spa tesseract-sun tesseract-swa tesseract-swe tesseract-tgk tesseract-tam tesseract-tel tesseract-tha tesseract-tur tesseract-ukr tesseract-urd tesseract-uzb tesseract-vie tesseract-cym tesseract-yid tesseract-yor

    - name: Install system dependencies
      run: choco install pulseaudio

    - name: Install xvfb
      run: choco install xvfb

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run pytest
      run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' pytest tests
